name: Cheshire-Cat Action on Pull Requests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop, codecov]

jobs:
  # pylint:
  #   name: "Coding Standards"
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./core
  #   strategy:
  #     matrix:
  #       python-version: ["3.10"]
  #   steps:
  #     - name: Download
  #       uses: actions/checkout@v3
  #     - name: Prepare Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: ${{ matrix.python-version }}
  #         cache: 'pip'
  #         cache-dependency-path: pyproject.toml
  #     - name: Download python dependencies
  #       run: pip install .[dev]
  #     - name: Pylint
  #       run: pylint -f actions ./
  test:
    # needs: [ pylint ]
    name: "Run Tests"
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Cat up
        run: docker-compose up -d
      - name: Test
        run: docker exec cheshire_cat_core python -m pytest --color=yes --cov --cov-report=html:core/coverage_re .
      - name: Cat down
        run: docker-compose down
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
